[project]
site_name = "DataTable2 Documentation"
title = "DataTable2 Docs"
description = "DataTable2 Documentation"
authors = ["pablissimo77"]
page_url = "https://datatable2.github.io"
nav = [
  { "Home" = "index.md" },
  { "Швидкий старт" = "quickstart.md" },
  { "Інтерфейс" = "interface.md" },
  { "Основні поняття" = "concepts.md" },
  { "Advanced" = [
    "advanced/advanced.md",
    "advanced/filters.md",
    "advanced/frm-data.md",
    "advanced/interface.md",
    "advanced/questions.md",
    "advanced/tables.md",
  ] },
  { "Download" = "download.md" },
  { "Changelog" = "changelog.md" },
  { "ToDo" = "todo.md" },
  { "Eula" = "eula.md" },
  { "Credits" = "credits.md" }

]

[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.zensical.extensions.glightbox]
auto_caption = true
[project.markdown_extensions.pymdownx.blocks.caption]


[project.theme]
name = "material"
logo = "assets/DataTable2.png"
favicon = "assets/DataTable2.ico"
language = "uk"


[build]
static_dir = "docs/assets"

#[project.extra]
#alternate = [
#    { name = "Ukrainian", link = "/uk/", lang = "uk" },
#    { name = "English", link = "/en/", lang = "en" }
#]
